### PR TITLE
Fixed Runscene syntax

### PR DESCRIPTION
**Pull request by rafale77**

### CODE REVIEW

**Review by akbooer — COMMENTED** [review]
Trying to see what this fixes?  Functionally the same, of course, but does avoid passing on any other parameters.

**Comment by rafale77** [comment]
The previous syntax for some reason no longer works after I pulled the latest changes on the dev branch. This makes it use the same syntax as the house mode change function.

**Comment by akbooer** [comment]
Worrying.  I don’t like to change things without knowing why, but I’ll take a look, thanks.

**Comment by akbooer** [comment]
Haven’t been able to duplicate any problem, and, TBH, it would be very hard to explain why there would be any difference...

**Comment by rafale77** [comment]
I can't explain this either. The old syntax still works in scenes Lua code but not here. I noticed it when some of my scenes stopped triggering after updating openLuup and this is how I got them working again. Might be a change in ALTUI? not sure.

**Pull request closed without merging**
