### PR TITLE
motion sensors specific LastTrip behavior

### PR DESCRIPTION
**Pull request by rafale77**
prevent motion sensor self reset from being a recorded as a trip event

### CODE REVIEW

**Review by akbooer — COMMENTED** [review]
I wonder if the serviceId hereshould be openLuup rather than SecuritySensor1 ?

**Comment by rafale77** [comment]
Not sure why that would be? Can you clarify?

Side note, I noticed you updated the ace URL for the console in the init.lua but it is redefined again in the console.lua file. Not sure if this was intended.

**Comment by akbooer** [comment]
Because these are not variables defind in the service file, and they are openLuup additions.

...on the other topic, the reference you found in the console is just a comment, not a redefinition of the variable.

**Comment by akbooer** [comment]
Did you decide that this wasn't necessary in the end? (ie. it _does_ reflect Vera's actual behaviour.)

**Comment by rafale77** [comment]
I decided to keep my changes for my installation as it is rather simple but I can see how it may be a breaking change for someone somewhere. The addition of another variable to reflect the actual LastTrip time would be a safer way to do it but unless someone else also is asking for it, it may not be worth the effort for my use case. I think this can be closed.

**Pull request closed without merging**
