### PR TITLE
if socket request is empty just close it

### PR DESCRIPTION
**Pull request by bfocht**
@akbooer 

In the logs I am seeing errors for sockets requests that have no data in them.  I am thinking these can be safely ignored.

 This might just be a result of my apache proxy doing a health check.

### CODE REVIEW

**Comment by akbooer** [comment]
Need a bit more info on this before making any change.  What are the headers of the empty requests?

**Comment by bfocht** [comment]
There aren't any headers.  Its just an empty value returned by `sock:receive()`

I did some testing to reproduce it an it is actually most often seen when I am using the _Imperihome_ android app.  Which means its not going through the Apache proxy but is a direct request to port 3480

I suspect the app just sends an empty value periodically to keep the connection open for reuse.

**Comment by akbooer** [comment]
OK, I misunderstood... 
It sounds like Imperihome shouldn't do that - there's a better low-level way to keep a TCP connection alive than just sending empty packets. However, we have to deal with it.  I see that you don't actually close the connection, but return "closed".  I'm still unsure of the impact of doing that on other things.

**Comment by bfocht** [comment]
Yah, I originally _closed_ the connection, but then found that the client was still reusing the connection so I deleted that line.   

I return an `err` otherwise this code executes and errors https://github.com/akbooer/openLuup/blob/development/openLuup/server.lua#L391

I set the error response to `closed` to get past this if check
https://github.com/akbooer/openLuup/blob/development/openLuup/server.lua#L411

The reality is that I can change the code around, but wanted to keep the initial change simple to identify the issue and also not unknowingly break something else.

**Comment by bfocht** [comment]
hmmm, I see that the chrome browser on android is doing the same thing.  sending empty packets...   I suspect its something with in the android operating system.

**Pull request closed without merging**
